### ISSUE TITLE
Widget font transparency setting

### ISSUE THREAD

**Issue by evedenlijuen** [FossifyOrg/Notes#19]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

We already had a widget background transparency setting, but It would be very nice to have a widget font transparency setting too.

### Why do you want this feature?

That would make the app more versatile and conveniant to create aesthetic and/or hidden note links on the home screens.

### Additional information

I think this feature would be nice in every fossify app widgets.

Thank you for the hard work !

**Comment by tusharwebd** [comment]
Hi @evedenlijuen! I am a new contributor here and would be interested to work on this issue. Can you assign this to me? Thanks!

**Comment by Aga-C** [comment]
@tusharwebd Please don't work on this issue until `needs triage` label is taken off.

**Comment by naveensingh** [comment]
Thanks for filing the issue but transparent fonts don't sound like a very good idea to me.
