### ISSUE TITLE
Automatically shift (un)selected items in list

### ISSUE THREAD

**Issue by ojppe** [FossifyOrg/Notes#40]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Move or option to automatically move selected items down, and unselected items up in a list

### Why do you want this feature?

Long (shopping) lists become hard to navigate when (un)selected items are not automatically moved to another section

**Comment by Aga-C** [comment]
- If by selected you mean an item on which you've long tapped, there are buttons to move selection to the top or the bottom.
- If by selected you mean completed, you can set in sorting to always move completed items to the bottom. However, it doesn't work with custom sorting.

Do you mean one of these, or something different?

**Comment by ojppe** [comment]
> you can set in sorting to always move completed items to the bottom. However, it doesn't work with custom sorting.
> 

This. But I'd like it to happen automatically. And for uncompleted items to move to the top

**Comment by naveensingh** [comment]
Actually, I wanted to move the the checked items to a collapsible section at the end of the list similar to how it is done in Google Keep, Google Tasks.
