### ISSUE TITLE
Fossify Thank You app is offered but does not exist

### ISSUE THREAD

**Issue by GuitarBilly** [FossifyOrg/Notes#44]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Notes/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 7.1.2

### Affected device model

Nokia 6 - TA-1033

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. start Fossify Notes many times.
2. wait for the message about Fossify Thank You (Fossify Bedankje) to appear.
3. press Buy (Kopen).

### Expected behavior

I would expect one of two things in the future:
- create and offer Fossify Thank You.
- remove Fossify Thank You.

### Actual behavior

Once you press Buy,  Google Play opens to notify an error that the item cannot be found.

### Screenshots/Screen recordings

<img alt="Screenshot_20240513-080051 blr" src="https://github.com/FossifyOrg/Notes/assets/38086529/00f5b84c-affe-4357-bdc6-33808c5df40a" width=225 />
<img alt="Screenshot_20240513-080104" src="https://github.com/FossifyOrg/Notes/assets/38086529/3bb6f0fd-4097-4d11-b9bd-db13500c5065" width=225 />

### Additional information

I realize that this potentially affects all Fossify apps  as ¨ThankYouInstalled" is in many places in the code, enherited from SMT.

My reasoning for posting it here is simple: the Notes app is the one that brought me the message.

**Comment by naveensingh** [comment]
Thanks for the heads up. Fossify Thank You will be released soon with the other apps that's why the code is still there, though I should have disabled the popup for the time being.

**Comment by naveensingh** [comment]
I'm closing this in favor of the google play availability thread. I'll post an update once it is released.
