### ISSUE TITLE
# SUGGESTIONS

### ISSUE THREAD

**Issue by UserAccount123** [FossifyOrg/Notes#56]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Notes/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.0

### Affected Android/Custom ROM version

Android 12

### Affected device model

Xiaomi Redmi 9

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

?

### Expected behavior

Adding these new features.

### Actual behavior

?

### Additional information

# Suggestions:
* Add option to disable/enable (Tabs) feature; If you added disabling feature, please do these suggestions:
* Put all notes together in a main screen.
* Ability to hide notes.
* Add (+) icon to create a note + swipe up to create list note + long press to view hidden/locked notes (add lock with password feature).
* Add (Archive + Recycle bin) features + Add (Empty) option in both of them to clear all items.
* Automatically delete empty note/checklist (don't put them in archive or recycle bin).
* Inside the note make the background in white color, but to distinguish between notes add an ability to add colors for notes (editable by the user: red, yellow, ...) (+ if someone added a strong color to note (Deep blue, deep red color, ..) please make the text color in white color; for easy reading).
* Option to group notes by color/alphabet/modification date/creation date.
* Ability to reorder notes by drag & drop (and if grouping by color is enabled .. deny/forbid moving a note away from notes with same color).
* Ability to change font size of notes viewed in main screen.
* Ability to specify numbers of lines to view in notes in main screen.
* Ability to only show title of the note (hiding its content) + if searching a word, temporarily disable (Show only title) option if it's enabled.
* Ability to hide/show (creation/modification) date in note.
* Swipe notes to: delete/archive/lock/put favourite mark.
* Search:
1.  Ability to search text in ALL notes + Highlight ALL the texts with color and automatically scroll to them by arrow buttons.
2. Ability to search text while editing a note/checklist & highlight ALL the texts AND automatically scroll to them by arrow buttons + Keep highlighting active until you start typing a word.
* Long press (Undo) icon to remove all changes are made.
* Ability to insert clipboard text by floating shape or by viewing the clipboard text as floating text object.
* Add (Character count + Copy note content to clipboard) feature for note & checklist.
* (Replace text) feature .. put inside a note/checklist, AND an ability to replace text in multiple notes (notes/checklists).
* Ability to export multiple selected notes (TXT, PNG/JPG, PDF).

# Suggestions in checklist:
* Insert list items directly without opening a pop-up window.
* Option to disable/enable collapsing feature of checked items .. And when disabling collapsing feature just put the items in the bottom.
* Make (=) reorder mark always visible without long pressing the item (and when moving an item make it not transparent; to avoid overlapping texts on top of each other) + If someone want to move many items together .. Add an ability to temporarily group list items so as to move them together.
* Always show (X) sign next ALL items, instead of (Delete) icon.
* I suggest pressing keyboard's (ENTER) key to insert new line after current line you're in, instead of adding it at the bottom.
* FEATURE: Swipe left a checklist line to change it to a normal line (without checkbox) + Swipe right to add color to it; from the idea of: lines with similar contents has the same color.
-------------
* FEATURE: convert checklist to a shopping list note, that has these features:
- Option to WRITE currency sign.
- Ability to directly add new item's price and quantity.
- Show the result of multiplying (Quantity x Price) beside the item.
- Move checked items to bottom + and if unchecked restore it back to the original position.
- Swipe item to delete.
- Feature of calculating cost of (total price, checked items, unchecked items).
- Add button to remove checked items (swipe it up to remove ALL items without confirmation).
- Ability to add color to lines of items (; to distinguish a group of items from each other).
* Widget: show checkbox beside items (not a circle sign) + Show price, quantity and the result of (Quantity x Price).

# WIDGET:
* Add these types of widgets:
- If you choose checklist widget .. Show checkboxes (not circle marks).
- A widget shows all notes (and option to specify number of lines to show) + (+) Button to quickly create new note/checklist.
* Make the corners of widget in square shape, or decrease the angle of the curve.

**Comment by Aga-C** [comment]
> This issue contains only one bug.
