### ISSUE TITLE
Implement backup retention options

### ISSUE THREAD

**Issue by linesquarecube** [FossifyOrg/Notes#67]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Implement a flexible backup retention system that allows users to control the timespan or quantity of automatic backups

### Why do you want this feature?

As a user, I want to limit the number of backup files or set a retention period for backups because:
1.  I currently have 215 .json backup files created at irregular intervals.
2.  This large number of files reduces overview and organization.
3.  It unnecessarily consumes storage space on my phone.
4.  A limit of 3 to 5 backup files or a one-week retention period would be sufficient for my needs.

This feature would help me maintain a manageable number of backups while ensuring efficient use of my phone's storage.

**Comment by Aga-C** [comment]
Closing in favor of FossifyOrg/General-Discussion#259.
