### ISSUE TITLE
Change the Edit symbol

### ISSUE THREAD

**Issue by Mr-Bajs** [FossifyOrg/Notes#71]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When editing a note the Fossify Notes app uses a very odd symbol for editing. It's goes against modern android and/or computer symbol conventions overall. I guess more symbols are about to change in an update, however I found that it stood out as an particulary bad symbol.
It should be updated to something like the material symbols.

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:edit:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=edit&icon.size=24&icon.color=%235f6368
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:edit_note:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=edit&icon.size=24&icon.color=%235f6368

I'll guess it's on the roadmap with a change from checkboxes to switches etc.

### Why do you want this feature?

.

**Comment by Aga-C** [comment]
Which edit icon do you mean? The one in the checklist to edit the item after long pressing it?

**Comment by naveensingh** [comment]
Will be fixed in the next update.
