### ISSUE TITLE
Add text password please

### ISSUE THREAD

**Issue by jekv2** [FossifyOrg/Notes#78]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add text password please

### Why do you want this feature?

Passwords are easier to recall.

### Additional information

Went to migrate from fast notepad, realized notes doesn't have lock notes with password.

**Comment by Aga-C** [comment]
Do you mean to lock notes with a password, or give the ability to provide a text password instead of a PIN or a fingerprint?

**Comment by jekv2** [comment]
> Do you mean to lock notes with a password, or give the ability to provide a text password instead of a PIN or a fingerprint?
lock note with password.

**Comment by jekv2** [comment]
> Do you mean to lock notes with a password, or give the ability to provide a text password instead of a PIN or a fingerprint?

lock note with password.

**Comment by Aga-C** [comment]
You can already do it by selecting `Lock note` from the three dots menu.

**Comment by jekv2** [comment]
> You can already do it by selecting `Lock note` from the three dots menu.

yes, but no way to use a password protect the note, only pattern or pin.
![Screenshot_20241206-135322](https://github.com/user-attachments/assets/415a13bc-2e36-40f9-9a4f-00977b487703)
