### ISSUE TITLE
Support for shared content URI's for automatic backups

### ISSUE THREAD

**Issue by jasger9000** [FossifyOrg/Notes#84]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When enabling the automatic backup function, it is only possible to back up files to a directory inside the `Internal` filesystem. It would however be great to be able to specify a shared URI to another storage location provided by a different application. For example, the app [CIFS Document provider](https://github.com/wa2c/cifs-documents-provider) provides a storage URI (`smb://<share_name>`) and a shared URI (`content://<appid>/tree/<share_id>`) to a remote SMB network share. If you were able to provide the shared URI to the backup function, you then would be able to back up your files to other storage systems, not just your device's one.

### Why do you want this feature?

I like to back up my files, not on the device on which the original copy is stored anyway, since if I were to lose my phone that wouldn't really be useful in any capacity. So when I want to back up my notes, I would either need to enable the automatic backups for an internal folder and then manually copy those over to my network share, or remember to manually export the notes myself. Either one of those is not ideal and also prone to just forgetting it, and therefore not a good solution.

### Additional information

The android file picker that's used if you manually export your notes supports remote locations (like Google Drive or CIFS), however I don't know the implementation details for that feature, and my guess is that it just returns a file descriptor. But if not, it may be possible to use it to pick a remote location, instead of the current system, so the user wouldn't need to know the shared URI to that location.

**Comment by Aga-C** [comment]
It should be done for all apps that have automatic backups. Please raise it in https://github.com/FossifyOrg/General-Discussion/issues.
